In [9]:
df_ttn.count()

NameError: name 'df_ttn' is not defined

In [ ]:
df_ttn.loc[:, 'alive'].value_counts()
df_ttn.loc[:, 'alive'].value_counts(normalize=True)*100

alive
no     549
yes    342
Name: count, dtype: int64

alive
no     61.616162
yes    38.383838
Name: proportion, dtype: float64

In [ ]:
df_ttn.loc[:, 'sex'].value_counts(normalize=True)*100

sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64

In [ ]:
df_ttn_sex_alive = df_ttn.loc[:, ['sex', 'alive']].value_counts(normalize=True)*100

In [ ]:
type(df_ttn_sex_alive)
df_ttn_sex_alive

pandas.core.series.Series

sex     alive
male    no       52.525253
female  yes      26.150393
male    yes      12.233446
female  no        9.090909
Name: proportion, dtype: float64

In [ ]:
df_ttn_sex_alive.index

NameError: name 'df_ttn_sex_alive' is not defined

In [ ]:
df = pd.DataFrame({
    '이름': ['홍길동', '김철수', '이영희', '박민수'],
    '나이': [25, 30, 28, 35],
    '급여': [3000, 4000, 3500, 5000]
}, index=[('a', 'b'), ('c', 'd'), ('e', 'f'), ('g', 'h')])
df

         이름  나이    급여
(a, b)  홍길동  25  3000
(c, d)  김철수  30  4000
(e, f)  이영희  28  3500
(g, h)  박민수  35  5000

### 5.4.7 객체 비교와 `id()` 함수 주의사항 (메모리 재활용)

`loc`이나 `iloc`을 사용하여 데이터를 선택할 때, 서로 다른 객체임에도 불구하고 `id()` 함수(메모리 주소)의 결과가 같게 나오는 경우가 있어 혼동을 줄 수 있습니다. 이는 Python의 **메모리 재활용 메커니즘** 때문입니다.

**현상**: 서로 다른 객체임에도 `id()` 값이 같게 나옴
**원인**: 임시 객체가 소멸된 후, 그 메모리 주소를 즉시 재활용하여 새 객체를 할당하기 때문
**해결**: 객체 비교는 `is` 연산자, 값 비교는 `==` 또는 `.equals()` 사용

In [ ]:
# 1. 서로 다른 객체인지 확인 (False가 정상)
print(f"df.iloc[0] is df.iloc[0]: {df.iloc[0] is df.iloc[0]}")

# 2. 주소값 확인 (같을 수 있음 - 메모리 재활용)
id1 = id(df.iloc[0])
id2 = id(df.iloc[0])
print(f"id(df.iloc[0]): {id1}")
print(f"id(df.iloc[0]): {id2}")
print(f"주소값 동일 여부: {id1 == id2}")

# 3. 올바른 값 비교 방법
print(f"값 동등성 비교 (.equals): {df.iloc[0].equals(df.iloc[0])}")

df.iloc[0] is df.iloc[0]: False
id(df.iloc[0]): 6066805456
id(df.iloc[0]): 6066805456
주소값 동일 여부: True
값 동등성 비교 (.equals): True

In [ ]:
import pandas as pd
import numpy as np

data = {
    'col1': [1, 2, 3, 4, 5],
    'col2': [10.1, 11.2, 12.3, 13.4, 14.5],
    'col3': [100, 200, 300, 400, 500],
    'col4': [1.0, 2.0, 3.0, 4.0, 5.0],
    'col5': [56, 6, 7, 44, 9] # Mixed type with NaN
}
df1 = pd.DataFrame(data)
print("==== df1 ====")
df1
df2 = df1.astype(int)
print("==== df2 ====")
df2
print("==== df1.iloc[0] ====")
df1.iloc[0]
print("==== df2.iloc[0] ====")
df2.iloc[0]
print("==== df1.iloc[0] is df2.iloc[0] ====")
df1.iloc[0] is df2.iloc[0]
print("==== df1.iloc[0] == df2.iloc[0] ====")
df1.iloc[0] == df2.iloc[0]
print("==== id(df1.iloc[0]) ====")
id(df1.iloc[0])
print("==== id(df2.iloc[0]) ====")
id(df2.iloc[0])
print("==== id(df1.iloc[0]), id(df2.iloc[0]) ====")
id(df1.iloc[0]), id(df2.iloc[0])
print("==== id(df1.iloc[0]) is id(df2.iloc[0]) ====")
id(df1.iloc[0]) is id(df2.iloc[0]) 
print("==== id(df1.iloc[0]) == id(df2.iloc[0]) ====")
id(df1.iloc[0]) == id(df2.iloc[0])

==== df1 ====

   col1  col2  col3  col4  col5
0     1  10.1   100   1.0    56
1     2  11.2   200   2.0     6
2     3  12.3   300   3.0     7
3     4  13.4   400   4.0    44
4     5  14.5   500   5.0     9

==== df2 ====

   col1  col2  col3  col4  col5
0     1    10   100     1    56
1     2    11   200     2     6
2     3    12   300     3     7
3     4    13   400     4    44
4     5    14   500     5     9

==== df1.iloc[0] ====

col1      1.0
col2     10.1
col3    100.0
col4      1.0
col5     56.0
Name: 0, dtype: float64

==== df2.iloc[0] ====

col1      1
col2     10
col3    100
col4      1
col5     56
Name: 0, dtype: int64

==== df1.iloc[0] is df2.iloc[0] ====

False

==== df1.iloc[0] == df2.iloc[0] ====

col1     True
col2    False
col3     True
col4     True
col5     True
Name: 0, dtype: bool

==== id(df1.iloc[0]) ====

6270856272

==== id(df2.iloc[0]) ====

6270854224

==== id(df1.iloc[0]), id(df2.iloc[0]) ====

(6270856272, 6270856272)

==== id(df1.iloc[0]) is id(df2.iloc[0]) ====

False

==== id(df1.iloc[0]) == id(df2.iloc[0]) ====

True