In [23]:
import pandas as pd
import numpy as np

In [24]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [25]:
data = {
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 263203],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"]
}
columns = ["도시", "연도", "인구", "지역"]
df1 = pd.DataFrame(data, columns=columns)
df1

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010   263203  수도권

In [26]:
# 각 도시에 대한 연도별 인구
df1.pivot_table(index="도시", columns="연도", values="인구")

연도       2005       2010       2015
도시
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN   263203.0  2890451.0

In [27]:
# 각 지역별 도시에 대한 연도별 인구
df1.pivot_table(index=["지역","도시"],columns="연도", values="인구")

연도           2005       2010       2015
지역  도시
경상권 부산  3512547.0  3393191.0  3448737.0
수도권 서울  9762546.0  9631482.0  9904312.0
    인천        NaN   263203.0  2890451.0

In [28]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset('titanic')[['age','sex','class','fare','survived']]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [29]:
# 선실 등급별로 숙박객의 성별 평균 나이
pdf1 = pd.pivot_table(df,                # 피벗할 데이터 프레임
                      index='class',     # 행 인덱스로 사용
                      columns='sex',     # 컬럼으로 사용
                      values='age',      # 계산 데이터로 사용할 열
                      aggfunc='mean',    # 데이터 집계 함수
                      observed=False     # 경고 해결: 범주형 데이터의 관측되지 않은 값도 포함 (기존 동작 유지) 기본값 False 향 후 True로 변경
                     )
pdf1

sex        female       male
class
First   34.611765  41.281386
Second  28.722973  30.740707
Third   21.750000  26.507589

In [34]:
# 선실 등급에 따른 성별에 대해 생존여부별로 나이와 티켓값의 평균과 최대값을 산출
pdf3 = pd.pivot_table(df,
    index = ['class','sex'],
    columns = 'survived',
    values = ['age','fare'],
    aggfunc = ['mean','max'],
    observed=False
)
pdf3

                    mean                                      max        \
                     age                   fare               age
survived               0          1           0           1     0     1
class  sex
First  female  25.666667  34.939024  110.604167  105.978159  50.0  63.0
       male    44.581967  36.248000   62.894910   74.637320  71.0  80.0
Second female  36.000000  28.080882   18.250000   22.288989  57.0  55.0
       male    33.369048  16.022000   19.488965   21.095100  70.0  62.0
Third  female  23.818182  19.329787   19.773093   12.464526  48.0  63.0
       male    27.255814  22.274211   12.204469   15.579696  74.0  45.0


                 fare
survived            0         1
class  sex
First  female  151.55  512.3292
       male    263.00  512.3292
Second female   26.00   65.0000
       male     73.50   39.0000
Third  female   69.55   31.3875
       male     69.55   56.4958

In [31]:
np.random.seed(0)
df2 = pd.DataFrame({
'key1': ['A', 'A', 'B', 'B', 'A'],
'key2': ['one', 'two', 'one', 'two', 'one'],
'data1': [1, 2, 3, 4, 5],
'data2': [10, 20, 30, 40, 50]
})
df2

  key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
2    B  one      3     30
3    B  two      4     40
4    A  one      5     50

In [33]:
groups = df2.groupby(df2.key1)
groups
groups.groups

{'A': [0, 1, 4], 'B': [2, 3]}

In [38]:
groups.groups.keys()
groups.groups['A']
groups.groups.values()
groups.groups.items()

dict_keys(['A', 'B'])

Index([0, 1, 4], dtype='int64')

dict_values([Index([0, 1, 4], dtype='int64'), Index([2, 3], dtype='int64')])

dict_items([('A', Index([0, 1, 4], dtype='int64')), ('B', Index([2, 3], dtype='int64'))])

In [57]:
df1 = pd.DataFrame(groups)
df1
df1.loc[0,1]

   0                                                  1
0  A    key1 key2  data1  data2
0    A  one      1  ...
1  B    key1 key2  data1  data2
2    B  one      3  ...

  key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
4    A  one      5     50

In [56]:
pd.DataFrame(groups).loc[0].values

array(['A',   key1 key2  data1  data2
            0    A  one      1     10
            1    A  two      2     20
            4    A  one      5     50], dtype=object)

In [58]:
pd.DataFrame(groups).loc[1].values

array(['B',   key1 key2  data1  data2
            2    B  one      3     30
            3    B  two      4     40], dtype=object)

In [59]:
pd.DataFrame(groups).loc[1].values[1]

  key1 key2  data1  data2
2    B  one      3     30
3    B  two      4     40

In [60]:
groups.sum()

           key2  data1  data2
key1
A     onetwoone      8     80
B        onetwo      7     70

In [66]:
type(groups)
groups.sum()
type(groups['data1'])
groups['data1'].sum()
groups.sum()['data1']

pandas.core.groupby.generic.DataFrameGroupBy

           key2  data1  data2
key1
A     onetwoone      8     80
B        onetwo      7     70

pandas.core.groupby.generic.SeriesGroupBy

key1
A    8
B    7
Name: data1, dtype: int64

key1
A    8
B    7
Name: data1, dtype: int64

In [67]:
groups[['data1']].sum()
groups[['data2']].sum()

      data1
key1
A         8
B         7

      data2
key1
A        80
B        70

In [74]:
for _, group in groups:
    print('_ :\n',_)
    print('group :\n',group)
    print(type(group))

_ :
 A
group :
   key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
4    A  one      5     50
<class 'pandas.core.frame.DataFrame'>
_ :
 B
group :
   key1 key2  data1  data2
2    B  one      3     30
3    B  two      4     40
<class 'pandas.core.frame.DataFrame'>

In [75]:
for x in groups:
    print('x :\n',x)
    print(type(x))

x :
 ('A',   key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
4    A  one      5     50)
<class 'tuple'>
x :
 ('B',   key1 key2  data1  data2
2    B  one      3     30
3    B  two      4     40)
<class 'tuple'>

In [76]:
import seaborn as sns
iris = sns.load_dataset("iris")
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [80]:
#iirs 품종별로 그룹
i_groups = iris.groupby('species')
i_groups.mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [85]:
i_groups.petal_length.sum()
i_groups['petal_length'].sum()

species
setosa         73.1
versicolor    213.0
virginica     277.6
Name: petal_length, dtype: float64

species
setosa         73.1
versicolor    213.0
virginica     277.6
Name: petal_length, dtype: float64

In [88]:
i_groups.max()
i_groups.min()
i_groups.max()/i_groups.min()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          1.348837     1.913043      1.900000     6.000000
versicolor      1.428571     1.700000      1.700000     1.800000
virginica       1.612245     1.727273      1.533333     1.785714

In [94]:
def peak_to_peak_ratio(x): # x는 시리즈
    # print(x.max())
    # print(x.min())
    return x.max() / x.min() # 함수 반환 값이 수치 스칼라 타입
peak_to_peak_ratio(iris.sepal_length)

1.8372093023255816

In [97]:
i_groups.agg(peak_to_peak_ratio)
i_groups.agg(['mean', 'std'])
i_groups.agg({'sepal_length':'mean', 'sepal_width':'std', 'petal_length':'max'})

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          1.348837     1.913043      1.900000     6.000000
versicolor      1.428571     1.700000      1.700000     1.800000
virginica       1.612245     1.727273      1.533333     1.785714

           sepal_length           sepal_width           petal_length  \
                   mean       std        mean       std         mean
species
setosa            5.006  0.352490       3.428  0.379064        1.462
versicolor        5.936  0.516171       2.770  0.313798        4.260
virginica         6.588  0.635880       2.974  0.322497        5.552

                     petal_width
                 std        mean       std
species
setosa      0.173664       0.246  0.105386
versicolor  0.469911       1.326  0.197753
virginica   0.551895       2.026  0.274650

            sepal_length  sepal_width  petal_length
species
setosa             5.006     0.379064           1.9
versicolor         5.936     0.313798           5.1
virginica          6.588     0.322497           6.9

In [98]:
i_groups.agg(lambda x: x.max() / x.min())

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          1.348837     1.913043      1.900000     6.000000
versicolor      1.428571     1.700000      1.700000     1.800000
virginica       1.612245     1.727273      1.533333     1.785714

In [117]:
def top3_petal_length(df):
    print(type(df))
    return df.sort_values(by="petal_length", ascending=False)[:4]
# 함수 반환값이 수치 집합(df가 반환됨)
# type(top3_petal_length(iris))
top3_petal_length(iris)

<class 'pandas.core.frame.DataFrame'>

     sepal_length  sepal_width  petal_length  petal_width    species
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica

In [118]:
i_groups.apply(top3_petal_length)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_51975/2449036750.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  i_groups.apply(top3_petal_length)

                sepal_length  sepal_width  petal_length  petal_width  \
species
setosa     24            4.8          3.4           1.9          0.2
           44            5.1          3.8           1.9          0.4
           23            5.1          3.3           1.7          0.5
           5             5.4          3.9           1.7          0.4
versicolor 83            6.0          2.7           5.1          1.6
           77            6.7          3.0           5.0          1.7
           72            6.3          2.5           4.9          1.5
           52            6.9          3.1           4.9          1.5
virginica  118           7.7          2.6           6.9          2.3
           117           7.7          3.8           6.7          2.2
           122           7.7          2.8           6.7          2.0
           105           7.6          3.0           6.6          2.1

                   species
species
setosa     24       setosa
           44       setosa
           23       setosa
           5        setosa
versicolor 83   versicolor
           77   versicolor
           72   versicolor
           52   versicolor
virginica  118   virginica
           117   virginica
           122   virginica
           105   virginica

In [133]:
# i_groups.agg(top3_petal_length)
# agg에 적용된 함수의 반환값이 수치 스칼라가 아니기때문에
# ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
def q3cut(s):
    # print(type(s))
    return pd.qcut(s, 3, labels=["소", "중", "대"]).astype(str)
iris.groupby("species").petal_length.apply(q3cut)

species
setosa     0      소
           1      소
           2      소
           3      중
           4      소
                 ..
virginica  145    소
           146    소
           147    소
           148    중
           149    소
Name: petal_length, Length: 150, dtype: object

In [132]:
q3cut(iris.petal_length)

0      소
1      소
2      소
3      소
4      소
      ..
145    대
146    대
147    대
148    대
149    대
Name: petal_length, Length: 150, dtype: object

In [144]:
iris.head(1)
iris.shape

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

(150, 5)

In [146]:
iris.min()
i_groups.min()

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [147]:
iris.groupby(iris.species).petal_length.apply(q3cut)

species
setosa     0      소
           1      소
           2      소
           3      중
           4      소
                 ..
virginica  145    소
           146    소
           147    소
           148    중
           149    소
Name: petal_length, Length: 150, dtype: object

In [148]:
iris['petal_length_class'] = iris.groupby(iris.species).petal_length.apply(q3cut).reset_index(drop=True)
iris.head()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_length_class
0,5.1,3.5,1.4,0.2,setosa,소
1,4.9,3.0,1.4,0.2,setosa,소
2,4.7,3.2,1.3,0.2,setosa,소
3,4.6,3.1,1.5,0.2,setosa,중
4,5.0,3.6,1.4,0.2,setosa,소

In [151]:
tips = sns.load_dataset("tips")
tips.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [152]:
tips['tip_pt'] = tips['tip'] / tips['total_bill']
tips.head()
tips.tail()

   total_bill   tip     sex smoker  day    time  size    tip_pt
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3  0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2  0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4  0.146808

     total_bill   tip     sex smoker   day    time  size    tip_pt
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

In [154]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
 7   tip_pt      244 non-null    float64
dtypes: category(4), float64(3), int64(1)
memory usage: 9.3 KB

In [155]:
tips.describe()

       total_bill         tip        size      tip_pt
count  244.000000  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672    0.160803
std      8.902412    1.383638    0.951100    0.061072
min      3.070000    1.000000    1.000000    0.035638
25%     13.347500    2.000000    2.000000    0.129127
50%     17.795000    2.900000    2.000000    0.154770
75%     24.127500    3.562500    3.000000    0.191475
max     50.810000   10.000000    6.000000    0.710345

In [165]:
iris.head()
i_groups.describe()
i_groups['sepal_length'].describe()
i_groups['sepal_width'].describe()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_length_class
0,5.1,3.5,1.4,0.2,setosa,소
1,4.9,3.0,1.4,0.2,setosa,소
2,4.7,3.2,1.3,0.2,setosa,소
3,4.6,3.1,1.5,0.2,setosa,중
4,5.0,3.6,1.4,0.2,setosa,소

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.428  ...        1.575  1.9        50.0  0.246
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.105386  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

            count   mean       std  min    25%  50%  75%  max
species
setosa       50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor   50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica    50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

            count   mean       std  min    25%  50%    75%  max
species
setosa       50.0  3.428  0.379064  2.3  3.200  3.4  3.675  4.4
versicolor   50.0  2.770  0.313798  2.0  2.525  2.8  3.000  3.4
virginica    50.0  2.974  0.322497  2.2  2.800  3.0  3.175  3.8

In [166]:
tips

     total_bill   tip     sex smoker   day    time  size    tip_pt
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]

In [177]:
t_groups = tips.groupby('sex', observed=True)
test_df = pd.DataFrame(t_groups)
test_df.loc[1][1].head(2)
test_df.loc[0][1].head(2)

   total_bill   tip     sex smoker  day    time  size    tip_pt
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
4       24.59  3.61  Female     No  Sun  Dinner     4  0.146808

   total_bill   tip   sex smoker  day    time  size    tip_pt
1       10.34  1.66  Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50  Male     No  Sun  Dinner     3  0.166587

In [178]:
# 성별 인원수를 계산
# 모든열에 결측치가 없으므로 모든열의 성별 인원수는 동일
t_groups.count()
t_groups.size() # 그룹내의 원소의 개수를 반환

        total_bill  tip  smoker  day  time  size  tip_pt
sex
Male           157  157     157  157   157   157     157
Female          87   87      87   87    87    87      87

sex
Male      157
Female     87
dtype: int64

In [187]:
# 흡연 유무에 따른 성별 인원
t_gp = tips.groupby(['sex','smoker'], observed=True)
# pd.DataFrame(t_gp).loc[3][1]
t_gp.size()
# 남성 여성 모두 비 흡연자수가 많다

sex     smoker
Male    Yes       60
        No        97
Female  Yes       33
        No        54
dtype: int64

In [189]:
# 흡연 유무에 따른 성별 인원을 피봇테이블로 구현
tips.pivot_table(values='total_bill',index='sex',columns='smoker',aggfunc='count', observed=True)

smoker  Yes  No
sex
Male     60  97
Female   33  54

In [191]:
# 성별 팁 비율의 평균
tips.groupby('sex', observed=True)['tip_pt'].mean()
# 여성이 식사금액 대비 팁 비율의 평균이 근소하게 높다

sex
Male      0.157651
Female    0.166491
Name: tip_pt, dtype: float64

In [193]:
# 흡연 유무에 따른 팁 비율의 평균
tips.groupby('smoker', observed=True)['tip_pt'].mean()
# 흡연자가 비 흡연자에 비해 팁비율이 근소하게 높다

smoker
Yes    0.163196
No     0.159328
Name: tip_pt, dtype: float64

In [195]:
# 성별과 흡연 유무에 따른 팁 비율의 평균
tips.pivot_table(values='tip_pt', index='sex',columns='smoker', observed=True)

smoker       Yes        No
sex
Male    0.152771  0.160669
Female  0.182150  0.156921

In [197]:
# 요일별 손님 수
tips.groupby('day', observed=True).size()

day
Thur    62
Fri     19
Sat     87
Sun     76
dtype: int64

In [198]:
len(tips)

244

In [201]:
# 요일별 여성/남성 손님 비율
tips.groupby(['day','sex'], observed=True).size()/len(tips)*100
# 여성 손님은 목요일에 비중이 높고 주말은 남성손님의 비중이 높다

day   sex
Thur  Male      12.295082
      Female    13.114754
Fri   Male       4.098361
      Female     3.688525
Sat   Male      24.180328
      Female    11.475410
Sun   Male      23.770492
      Female     7.377049
dtype: float64

In [203]:
# 요일별 테이블당 평균 인원 수
tips.groupby('day', observed=True)['size'].mean()

day
Thur    2.451613
Fri     2.105263
Sat     2.517241
Sun     2.842105
Name: size, dtype: float64

In [205]:
# 요일별 평균 팁 비율
tips.groupby('day')['tip_pt'].mean()

/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_51975/2863852490.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('day')['tip_pt'].mean()

day
Thur    0.161276
Fri     0.169913
Sat     0.153152
Sun     0.166897
Name: tip_pt, dtype: float64

In [206]:
# 요일별 평균 식사금액과 평균 팁
tips.groupby('day')[['total_bill','tip']].mean()

/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_51975/2060667421.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('day')[['total_bill','tip']].mean()

      total_bill       tip
day
Thur   17.682742  2.771452
Fri    17.151579  2.734737
Sat    20.441379  2.993103
Sun    21.410000  3.255132

In [213]:
tips.groupby(['day','sex','smoker'])['tip_pt'].mean()

/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_51975/3560279820.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['day','sex','smoker'])['tip_pt'].mean()

day   sex     smoker
Thur  Male    Yes       0.164417
              No        0.165706
      Female  Yes       0.163073
              No        0.155971
Fri   Male    Yes       0.144730
              No        0.138005
      Female  Yes       0.209129
              No        0.165296
Sat   Male    Yes       0.139067
              No        0.162132
      Female  Yes       0.163817
              No        0.147993
Sun   Male    Yes       0.173964
              No        0.158291
      Female  Yes       0.237075
              No        0.165710
Name: tip_pt, dtype: float64

In [218]:
tips.groupby(['day','sex','smoker'])['tip_pt'].mean().unstack()

/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_51975/4054963058.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['day','sex','smoker'])['tip_pt'].mean().unstack()

smoker            Yes        No
day  sex
Thur Male    0.164417  0.165706
     Female  0.163073  0.155971
Fri  Male    0.144730  0.138005
     Female  0.209129  0.165296
Sat  Male    0.139067  0.162132
     Female  0.163817  0.147993
Sun  Male    0.173964  0.158291
     Female  0.237075  0.165710

In [221]:
# 평균 통계량만 확인 했으므로 다른 통계값도 확인
tips.groupby(['sex', 'smoker'])[['tip_pt']].describe()

/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_51975/4012034184.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['sex', 'smoker'])[['tip_pt']].describe()

              tip_pt                                                    \
               count      mean       std       min       25%       50%
sex    smoker
Male   Yes      60.0  0.152771  0.090588  0.035638  0.101845  0.141015
       No       97.0  0.160669  0.041849  0.071804  0.131810  0.157604
Female Yes      33.0  0.182150  0.071595  0.056433  0.152439  0.173913
       No       54.0  0.156921  0.036421  0.056797  0.139708  0.149691


                    75%       max
sex    smoker
Male   Yes     0.191697  0.710345
       No      0.186220  0.291990
Female Yes     0.198216  0.416667
       No      0.181630  0.252672

In [223]:
df = pd.DataFrame({
    '부서': ['영업', '영업', '인사', '인사', '개발', '개발'],
    '팀': ['1팀', '2팀', '1팀', '2팀', '1팀', '2팀'],
    '연도': [2023, 2023, 2023, 2023, 2024, 2024],
    '매출': [100, 120, 80, 90, 150, 160],
    '비용': [50, 60, 40, 45, 70, 80]
})

df
# groupby 객체 생성
g = df.groupby('부서')
print(g)  # <pandas.core.groupby.generic.DataFrameGroupBy object at ...>

   부서   팀    연도   매출  비용
0  영업  1팀  2023  100  50
1  영업  2팀  2023  120  60
2  인사  1팀  2023   80  40
3  인사  2팀  2023   90  45
4  개발  1팀  2024  150  70
5  개발  2팀  2024  160  80

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x1766c44d0>

In [230]:
for name, group in g:
    print(f"=== {name} ===")
    print(group)

=== 개발 ===
   부서   팀    연도   매출  비용
4  개발  1팀  2024  150  70
5  개발  2팀  2024  160  80
=== 영업 ===
   부서   팀    연도   매출  비용
0  영업  1팀  2023  100  50
1  영업  2팀  2023  120  60
=== 인사 ===
   부서   팀    연도  매출  비용
2  인사  1팀  2023  80  40
3  인사  2팀  2023  90  45

In [232]:
# 부서와 연도별 그룹화
g_multi = df.groupby(['부서', '연도'])
g_multi

In [ ]:
for name, group in g:
    print(f"=== {name} ===")
    print(group)

=== 개발 ===
   부서   팀    연도   매출  비용
4  개발  1팀  2024  150  70
5  개발  2팀  2024  160  80
=== 영업 ===
   부서   팀    연도   매출  비용
0  영업  1팀  2023  100  50
1  영업  2팀  2023  120  60
=== 인사 ===
   부서   팀    연도  매출  비용
2  인사  1팀  2023  80  40
3  인사  2팀  2023  90  45

In [245]:
g_multi.sum()

            팀   매출   비용
부서 연도
개발 2024  1팀2팀  310  150
영업 2023  1팀2팀  220  110
인사 2023  1팀2팀  170   85

In [251]:
g.sum()

       팀    연도   매출   비용
부서
개발  1팀2팀  4048  310  150
영업  1팀2팀  4046  220  110
인사  1팀2팀  4046  170   85

In [ ]:
# 1. 여러 함수 동시 적용
print(type(df.groupby('부서')))
# print(df.groupby('부서').agg(['sum', 'mean', 'std']))
print(type(df.groupby('부서')['매출']))
print(df.groupby('부서')['매출'].agg(['sum', 'mean', 'std']))
print(type(df.groupby('부서')[['매출', '비용']]))
print(df.groupby('부서')[['매출', '비용']].agg(['sum', 'mean', 'std']))

# 2. 열마다 다른 함수 적용 (딕셔너리 활용)
agg_dict = {
    '매출': 'sum',       # 매출은 합계
    '비용': ['mean', 'max'] # 비용은 평균과 최대값
}
print(df.groupby('부서').agg(agg_dict))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
<class 'pandas.core.groupby.generic.SeriesGroupBy'>
    sum   mean        std
부서
개발  310  155.0   7.071068
영업  220  110.0  14.142136
인사  170   85.0   7.071068
<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
     매출                     비용
    sum   mean        std  sum  mean       std
부서
개발  310  155.0   7.071068  150  75.0  7.071068
영업  220  110.0  14.142136  110  55.0  7.071068
인사  170   85.0   7.071068   85  42.5  3.535534
     매출    비용
    sum  mean max
부서
개발  310  75.0  80
영업  220  55.0  60
인사  170  42.5  45

In [275]:
def range_func(x):
    """최대값과 최소값의 차이(범위) 계산"""
    return x.max() - x.min()

print(df.groupby('부서')['매출'].agg(range_func))
print(df.groupby('부서')[['매출', '비용']].agg(range_func))

부서
개발    10
영업    20
인사    10
Name: 매출, dtype: int64
    매출  비용
부서
개발  10  10
영업  20  10
인사  10   5

In [270]:
result = df.groupby('부서').agg(
    총매출=('매출', 'sum'),
    평균비용=('비용', 'mean'),
    최대매출=('매출', 'max')
)
print(result)

    총매출  평균비용  최대매출
부서
개발  310  75.0   160
영업  220  55.0   120
인사  170  42.5    90

In [277]:
# 부서별 매출 평균 계산
dept_mean = df.groupby('부서')['매출'].transform('mean')

# 원본 데이터에 '부서평균매출' 열 추가
df['부서평균매출'] = dept_mean
df['평균대비차이'] = df['매출'] - df['부서평균매출']
df

   부서   팀    연도   매출  비용  부서평균매출  평균대비차이
0  영업  1팀  2023  100  50   110.0   -10.0
1  영업  2팀  2023  120  60   110.0    10.0
2  인사  1팀  2023   80  40    85.0    -5.0
3  인사  2팀  2023   90  45    85.0     5.0
4  개발  1팀  2024  150  70   155.0    -5.0
5  개발  2팀  2024  160  80   155.0     5.0

In [279]:
# 매출 합계가 200 이상인 부서만 남기기
def filter_func(x):
    return x['매출'].sum() >= 250

filtered_df = df.groupby('부서').filter(filter_func)
print(filtered_df['부서'].unique())  # 매출 합계가 조건에 맞는 부서만 출력

['개발']

In [284]:
filtered_df2 = df.groupby('부서').filter(lambda x: x['비용'].max() > 50)
filtered_df2
print(filtered_df2['부서'].unique())  # 매출 합계가 조건에 맞는 부서만 출력

   부서   팀    연도   매출  비용  부서평균매출  평균대비차이
0  영업  1팀  2023  100  50   110.0   -10.0
1  영업  2팀  2023  120  60   110.0    10.0
4  개발  1팀  2024  150  70   155.0    -5.0
5  개발  2팀  2024  160  80   155.0     5.0

['영업' '개발']

In [289]:
def top_2_by_sales(x):
    """매출 기준 상위 2개 행 반환"""
    return x.sort_values('매출', ascending=False).head(2)
df.groupby('부서').apply(top_2_by_sales, include_groups=False)

       팀    연도   매출  비용  부서평균매출  평균대비차이
부서
개발 5  2팀  2024  160  80   155.0     5.0
   4  1팀  2024  150  70   155.0    -5.0
영업 1  2팀  2023  120  60   110.0    10.0
   0  1팀  2023  100  50   110.0   -10.0
인사 3  2팀  2023   90  45    85.0     5.0
   2  1팀  2023   80  40    85.0    -5.0

In [305]:
def mean_func(x):
    print(type(x))
    x["ttt"] = "aa"
    return x
df.groupby('부서').apply(mean_func, include_groups=False)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

       팀    연도   매출  비용  부서평균매출  평균대비차이 ttt
부서
개발 4  1팀  2024  150  70   155.0    -5.0  aa
   5  2팀  2024  160  80   155.0     5.0  aa
영업 0  1팀  2023  100  50   110.0   -10.0  aa
   1  2팀  2023  120  60   110.0    10.0  aa
인사 2  1팀  2023   80  40    85.0    -5.0  aa
   3  2팀  2023   90  45    85.0     5.0  aa

In [307]:
df
# 부서(행)와 연도(열)별 매출 합계
pivot = pd.pivot_table(
    df,
    values='매출',
    index='부서',
    columns='연도',
    aggfunc='sum',
    fill_value=0,  # 결측치 0으로 채움
    margins=True,  # 총계(All) 추가
    margins_name='총계'
)
print(pivot)

   부서   팀    연도   매출  비용  부서평균매출  평균대비차이
0  영업  1팀  2023  100  50   110.0   -10.0
1  영업  2팀  2023  120  60   110.0    10.0
2  인사  1팀  2023   80  40    85.0    -5.0
3  인사  2팀  2023   90  45    85.0     5.0
4  개발  1팀  2024  150  70   155.0    -5.0
5  개발  2팀  2024  160  80   155.0     5.0

연도  2023  2024   총계
부서
개발     0   310  310
영업   220     0  220
인사   170     0  170
총계   390   310  700

In [321]:
# 매출의 합계와 평균을 동시에
pivot_multi = pd.pivot_table(
    df,
    values=['매출', '비용'],
    index=['부서', '팀'],
    columns='연도',
    aggfunc={'매출': 'sum', '비용': 'mean'},
    fill_value=0
)
pivot_multi

        매출         비용
연도    2023 2024  2023  2024
부서 팀
개발 1팀    0  150   0.0  70.0
   2팀    0  160   0.0  80.0
영업 1팀  100    0  50.0   0.0
   2팀  120    0  60.0   0.0
인사 1팀   80    0  40.0   0.0
   2팀   90    0  45.0   0.0

In [327]:
# 샘플 데이터
data = pd.DataFrame({
    '성별': ['남', '여', '남', '여', '남'],
    '등급': ['A', 'B', 'A', 'A', 'B']
})

# 성별-등급별 빈도수
ct = pd.crosstab(data['성별'], data['등급'], margins=True)
ct

# 비율로 표시 (normalize)
ct_norm = pd.crosstab(data['성별'], data['등급'], normalize='index') # 행 기준 비율
ct_norm

등급   A  B  All
성별
남    2  1    3
여    1  1    2
All  3  2    5

등급         A         B
성별
남   0.666667  0.333333
여   0.500000  0.500000