In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [ ]:
data = {
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 263203],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"]
}
columns = ["도시", "연도", "인구", "지역"]
df1 = pd.DataFrame(data, columns=columns)
df1

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010   263203  수도권

In [ ]:
# 각 도시에 대한 연도별 인구
df1.pivot_table(index="도시", columns="연도", values="인구")

연도       2005       2010       2015
도시
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN   263203.0  2890451.0

In [ ]:
# 각 지역별 도시에 대한 연도별 인구
df1.pivot_table(index=["지역","도시"],columns="연도", values="인구")

연도           2005       2010       2015
지역  도시
경상권 부산  3512547.0  3393191.0  3448737.0
수도권 서울  9762546.0  9631482.0  9904312.0
    인천        NaN   263203.0  2890451.0

In [ ]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset('titanic')[['age','sex','class','fare','survived']]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [ ]:
# 선실 등급별로 숙박객의 성별 평균 나이
pdf1 = pd.pivot_table(df,                # 피벗할 데이터 프레임
                      index='class',     # 행 인덱스로 사용
                      columns='sex',     # 컬럼으로 사용
                      values='age',      # 계산 데이터로 사용할 열
                      aggfunc='mean',    # 데이터 집계 함수
                      observed=False     # 경고 해결: 범주형 데이터의 관측되지 않은 값도 포함 (기존 동작 유지) 기본값 False 향 후 True로 변경
                     )
pdf1

sex        female       male
class
First   34.611765  41.281386
Second  28.722973  30.740707
Third   21.750000  26.507589

In [ ]:
# 선실 등급에 따른 성별에 대해 생존여부별로 나이와 티켓값의 평균과 최대값을 산출
pdf3 = pd.pivot_table(df,
    index = ['class','sex'],
    columns = 'survived',
    values = ['age','fare'],
    aggfunc = ['mean','max'],
    observed=False
)
pdf3

                    mean                                      max        \
                     age                   fare               age
survived               0          1           0           1     0     1
class  sex
First  female  25.666667  34.939024  110.604167  105.978159  50.0  63.0
       male    44.581967  36.248000   62.894910   74.637320  71.0  80.0
Second female  36.000000  28.080882   18.250000   22.288989  57.0  55.0
       male    33.369048  16.022000   19.488965   21.095100  70.0  62.0
Third  female  23.818182  19.329787   19.773093   12.464526  48.0  63.0
       male    27.255814  22.274211   12.204469   15.579696  74.0  45.0


                 fare
survived            0         1
class  sex
First  female  151.55  512.3292
       male    263.00  512.3292
Second female   26.00   65.0000
       male     73.50   39.0000
Third  female   69.55   31.3875
       male     69.55   56.4958

In [ ]:
np.random.seed(0)
df2 = pd.DataFrame({
'key1': ['A', 'A', 'B', 'B', 'A'],
'key2': ['one', 'two', 'one', 'two', 'one'],
'data1': [1, 2, 3, 4, 5],
'data2': [10, 20, 30, 40, 50]
})
df2

  key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
2    B  one      3     30
3    B  two      4     40
4    A  one      5     50

In [ ]:
groups = df2.groupby(df2.key1)
groups
groups.groups

{'A': [0, 1, 4], 'B': [2, 3]}

In [ ]:
groups.groups.keys()
groups.groups['A']
groups.groups.values()
groups.groups.items()

dict_keys(['A', 'B'])

Index([0, 1, 4], dtype='int64')

dict_values([Index([0, 1, 4], dtype='int64'), Index([2, 3], dtype='int64')])

dict_items([('A', Index([0, 1, 4], dtype='int64')), ('B', Index([2, 3], dtype='int64'))])

In [ ]:
df1 = pd.DataFrame(groups)
df1
df1.loc[0,1]

   0                                                  1
0  A    key1 key2  data1  data2
0    A  one      1  ...
1  B    key1 key2  data1  data2
2    B  one      3  ...

  key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
4    A  one      5     50

In [ ]:
pd.DataFrame(groups).loc[0].values

array(['A',   key1 key2  data1  data2
            0    A  one      1     10
            1    A  two      2     20
            4    A  one      5     50], dtype=object)

In [ ]:
pd.DataFrame(groups).loc[1].values

array(['B',   key1 key2  data1  data2
            2    B  one      3     30
            3    B  two      4     40], dtype=object)

In [ ]:
pd.DataFrame(groups).loc[1].values[1]

  key1 key2  data1  data2
2    B  one      3     30
3    B  two      4     40

In [ ]:
groups.sum()

           key2  data1  data2
key1
A     onetwoone      8     80
B        onetwo      7     70

In [ ]:
type(groups)
groups.sum()
type(groups['data1'])
groups['data1'].sum()
groups.sum()['data1']

pandas.core.groupby.generic.DataFrameGroupBy

           key2  data1  data2
key1
A     onetwoone      8     80
B        onetwo      7     70

pandas.core.groupby.generic.SeriesGroupBy

key1
A    8
B    7
Name: data1, dtype: int64

key1
A    8
B    7
Name: data1, dtype: int64

In [ ]:
groups[['data1']].sum()
groups[['data2']].sum()

      data1
key1
A         8
B         7

      data2
key1
A        80
B        70

In [ ]:
for _, group in groups:
    print('_ :\n',_)
    print('group :\n',group)
    print(type(group))

_ :
 A
group :
   key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
4    A  one      5     50
<class 'pandas.core.frame.DataFrame'>
_ :
 B
group :
   key1 key2  data1  data2
2    B  one      3     30
3    B  two      4     40
<class 'pandas.core.frame.DataFrame'>

In [ ]:
for x in groups:
    print('x :\n',x)
    print(type(x))

x :
 ('A',   key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
4    A  one      5     50)
<class 'tuple'>
x :
 ('B',   key1 key2  data1  data2
2    B  one      3     30
3    B  two      4     40)
<class 'tuple'>

In [ ]:
import seaborn as sns
iris = sns.load_dataset("iris")
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
#iirs 품종별로 그룹
i_groups = iris.groupby('species')
i_groups.mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [ ]:
i_groups.petal_length.sum()
i_groups['petal_length'].sum()

species
setosa         73.1
versicolor    213.0
virginica     277.6
Name: petal_length, dtype: float64

species
setosa         73.1
versicolor    213.0
virginica     277.6
Name: petal_length, dtype: float64

In [ ]:
i_groups.max()
i_groups.min()
i_groups.max()/i_groups.min()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          1.348837     1.913043      1.900000     6.000000
versicolor      1.428571     1.700000      1.700000     1.800000
virginica       1.612245     1.727273      1.533333     1.785714

In [ ]:
def peak_to_peak_ratio(x): # x는 시리즈
    # print(x.max())
    # print(x.min())
    return x.max() / x.min() # 함수 반환 값이 수치 스칼라 타입
peak_to_peak_ratio(iris.sepal_length)

1.8372093023255816

In [ ]:
i_groups.agg(peak_to_peak_ratio)
i_groups.agg(['mean', 'std'])
i_groups.agg({'sepal_length':'mean', 'sepal_width':'std', 'petal_length':'max'})

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          1.348837     1.913043      1.900000     6.000000
versicolor      1.428571     1.700000      1.700000     1.800000
virginica       1.612245     1.727273      1.533333     1.785714

           sepal_length           sepal_width           petal_length  \
                   mean       std        mean       std         mean
species
setosa            5.006  0.352490       3.428  0.379064        1.462
versicolor        5.936  0.516171       2.770  0.313798        4.260
virginica         6.588  0.635880       2.974  0.322497        5.552

                     petal_width
                 std        mean       std
species
setosa      0.173664       0.246  0.105386
versicolor  0.469911       1.326  0.197753
virginica   0.551895       2.026  0.274650

            sepal_length  sepal_width  petal_length
species
setosa             5.006     0.379064           1.9
versicolor         5.936     0.313798           5.1
virginica          6.588     0.322497           6.9

In [ ]:
i_groups.agg(lambda x: x.max() / x.min())

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          1.348837     1.913043      1.900000     6.000000
versicolor      1.428571     1.700000      1.700000     1.800000
virginica       1.612245     1.727273      1.533333     1.785714

In [ ]:
def top3_petal_length(df):
    print(type(df))
    return df.sort_values(by="petal_length", ascending=False)[:4]
# 함수 반환값이 수치 집합(df가 반환됨)
# type(top3_petal_length(iris))
top3_petal_length(iris)

<class 'pandas.core.frame.DataFrame'>

     sepal_length  sepal_width  petal_length  petal_width    species
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica

In [ ]:
i_groups.apply(top3_petal_length)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_51975/2449036750.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  i_groups.apply(top3_petal_length)

                sepal_length  sepal_width  petal_length  petal_width  \
species
setosa     24            4.8          3.4           1.9          0.2
           44            5.1          3.8           1.9          0.4
           23            5.1          3.3           1.7          0.5
           5             5.4          3.9           1.7          0.4
versicolor 83            6.0          2.7           5.1          1.6
           77            6.7          3.0           5.0          1.7
           72            6.3          2.5           4.9          1.5
           52            6.9          3.1           4.9          1.5
virginica  118           7.7          2.6           6.9          2.3
           117           7.7          3.8           6.7          2.2
           122           7.7          2.8           6.7          2.0
           105           7.6          3.0           6.6          2.1

                   species
species
setosa     24       setosa
           44       setosa
           23       setosa
           5        setosa
versicolor 83   versicolor
           77   versicolor
           72   versicolor
           52   versicolor
virginica  118   virginica
           117   virginica
           122   virginica
           105   virginica

In [ ]:
# i_groups.agg(top3_petal_length)
# agg에 적용된 함수의 반환값이 수치 스칼라가 아니기때문에
# ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
def q3cut(s):
    # print(type(s))
    return pd.qcut(s, 3, labels=["소", "중", "대"]).astype(str)
iris.groupby("species").petal_length.apply(q3cut)

species
setosa     0      소
           1      소
           2      소
           3      중
           4      소
                 ..
virginica  145    소
           146    소
           147    소
           148    중
           149    소
Name: petal_length, Length: 150, dtype: object

In [ ]:
q3cut(iris.petal_length)

0      소
1      소
2      소
3      소
4      소
      ..
145    대
146    대
147    대
148    대
149    대
Name: petal_length, Length: 150, dtype: object