In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [37]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(10,22).reshape(3,4),
    index=['a','b','c'],
    columns = ["A","B","C","D"])
df
df.loc['a':'b', 'A']
df.iloc[0]

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

a    10
b    14
Name: A, dtype: int64

A    10
B    11
C    12
D    13
Name: a, dtype: int64

In [60]:
df['a':'b']
df[0:1]
df.loc['a':'b']
df.iloc[0:1]
df.loc['a':'b', 'A':'B']
df.loc['a':'b']['b':'b']
df2 = df.loc['a':'b']
df2
df2['b':'b']
df.iloc[0:1, 0:1]

    A   B   C   D
a  10  11  12  13
b  14  15  16  17

    A   B   C   D
a  10  11  12  13

    A   B   C   D
a  10  11  12  13
b  14  15  16  17

    A   B   C   D
a  10  11  12  13

    A   B
a  10  11
b  14  15

    A   B   C   D
b  14  15  16  17

    A   B   C   D
a  10  11  12  13
b  14  15  16  17

    A   B   C   D
b  14  15  16  17

    A
a  10

In [64]:
df.iloc[0:2, 0:-2]
df[0:1]
df['a':'c']
df.loc[['a','c']]

    A   B
a  10  11
b  14  15

    A   B   C   D
a  10  11  12  13

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

    A   B   C   D
a  10  11  12  13
c  18  19  20  21

In [65]:
df.loc['a']
df.loc[['a']]

A    10
B    11
C    12
D    13
Name: a, dtype: int64

    A   B   C   D
a  10  11  12  13

In [68]:
df.A
df.A > 15

a    10
b    14
c    18
Name: A, dtype: int64

a    False
b    False
c     True
Name: A, dtype: bool

In [70]:
df.loc[df.A>13]

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [75]:
def sel_row(df) :
    return df.A>11

In [76]:
sel_row(df)
df.loc[sel_row(df)]

a    False
b     True
c     True
Name: A, dtype: bool

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [78]:
df2 = pd.DataFrame(np.arange(10,26).reshape(4,4),
columns=['a','b','c','d'])
df2

    a   b   c   d
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [81]:
df2[1:2]
df2.loc[1:2]
df2.iloc[1:2]

    a   b   c   d
1  14  15  16  17

    a   b   c   d
1  14  15  16  17
2  18  19  20  21

    a   b   c   d
1  14  15  16  17

In [96]:
df2
df2.loc[0, 'a']

    a   b   c   d
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

np.int64(10)

In [97]:
df.loc['a', 'A']

np.int64(10)

In [98]:
df.loc['a', 'A'] = 50

In [99]:
df

    A   B   C   D
a  50  11  12  13
b  14  15  16  17
c  18  19  20  21

In [140]:
df.loc[['a','b']]
df.loc[['a','b']]['A'] # 시리즈
df.loc[['a','b'],'A'] # 시리즈
df.loc[['a','b'],['A']] # df 반환
df['a':'b']

    A   B   C   D
a  50  11  12  13
b  14  15  16  17

a    50
b    14
Name: A, dtype: int64

a    50
b    14
Name: A, dtype: int64

    A
a  50
b  14

    A   B   C   D
a  50  11  12  13
b  14  15  16  17

In [106]:
df2

    a   b   c   d
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [ ]:
df3 = pd.DataFrame(np.arange(10,26).reshape(4,4),
    columns=[2,3,5,6],
    index=[4,5,7,8]
    )
df3

    2   3   5   6
4  10  11  12  13
5  14  15  16  17
7  18  19  20  21
8  22  23  24  25

    a   b   c   d
0  10  11  12  13
1  14  15  16  17

In [136]:
df3[2:3]
df3.loc[2:3]
df3.iloc[2:3]

    2   3   5   6
7  18  19  20  21

Empty DataFrame
Columns: [2, 3, 5, 6]
Index: []

    2   3   5   6
7  18  19  20  21

In [145]:
df4 = pd.DataFrame({
    "A": [1,2,3],
    "B": [4,5,6],
    "C": [7,8,{"a":[1],"b":[2],"c":[3]}]
    },
    index=["a","b","c"]
)
df4

   A  B                               C
a  1  4                               7
b  2  5                               8
c  3  6  {'a': [1], 'b': [2], 'c': [3]}

In [149]:
df5 = pd.DataFrame(df4.loc["c", "C"])
df5

   a  b  c
0  1  2  3

In [165]:
df3.sort_index(ascending=False)
df3.sort_values(by=3, ascending=False)

    2   3   5   6
8  22  23  24  25
7  18  19  20  21
5  14  15  16  17
4  10  11  12  13

    2   3   5   6
8  22  23  24  25
7  18  19  20  21
5  14  15  16  17
4  10  11  12  13

In [173]:
type(df3.count())
df3.count()
df3.size

pandas.core.series.Series

2    4
3    4
5    4
6    4
dtype: int64

16